#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd

while IFS=: read -r username _ userid home_directory shell info; do
  echo "The user $username is part of the $userid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
