#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, displaying occurrence counts sorted from highest to lowest

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
