#!/usr/bin/env bash
# This script displays lines containing the word 'bash' to show the PID of Bash processes
# shellcheck disable=SC2009
ps -eH -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd | grep bash
