#!/usr/bin/env bash
# Kills the Highlander process

# Find the PID of the Highlander process
highlander_pid=$(pgrep -f "7-highlander")

# Check if the process was found
if [[ "$highlander_pid" != "" ]]; then
  # Kill the process
  kill "$highlander_pid"
  echo "Highlander process killed."
else
  echo "Highlander process not found."
fi
